name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11.8'
        cache: 'pip' # caching pip dependencies
        cache-dependency-path: 'requirements-lint.txt'
    - name: Check lint
      run: pip install -r requirements-lint.txt && ./scripts/lint.sh
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: kfstorm
        password: ${{ secrets.DOCKER_HUB_PAT }}
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        # List of target platforms for build
        platforms: linux/amd64,linux/arm64/v8
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: kfstorm/doudarr
        # Cache layers for faster builds
        cache-from: type=gha
        cache-to: type=gha,mode=max
