name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: kfstorm
        password: ${{ secrets.DOCKER_HUB_PAT }}
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        # List of target platforms for build
        platforms: linux/amd64,linux/arm64/v8
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: kfstorm/douban-to-radarr-list
              
